# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

# Required by RNFirebase
pod 'Firebase/Core'
pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

# [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
#pod 'Firebase/AdMob'
#pod 'Firebase/Auth'
#pod 'Firebase/Crash'
pod 'Firebase/Database'
#pod 'Firebase/DynamicLinks'
#pod 'Firebase/Messaging'
#pod 'Firebase/RemoteConfig'
#pod 'Firebase/Storage'


pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'BatchedBridge', # Required For React Native 0.45.0+
  'Core',
  # Add any other subspecs you want to use in your project
]

target 'PiPlant' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PiPlant

  target 'PiPlantTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PiPlant-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PiPlant-tvOS

  target 'PiPlant-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


#Also add this at the very bottom of your Podfile

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
